openapi: 3.0.0
info:
  title: Mangos Account API
  description: API allowing to interact with Mangos Accounts
  license:
    name: Apache 2.0
  version: "1.0"
externalDocs:
  description: Instructions on how to deploy this WebApp
  url: https://github.com/Warkdev/account-service/blob/master/README.md
servers:
- url: http://localhost:9081/account-service
tags:
- name: account
  description: Operations about accounts
- name: ban
  description: Operations about bans (accounts and IPs)
paths:
  /v1/{id}:
    get:
      tags:
      - account
      summary: Retrieves an account given the id
      description: This API is retrieving the account with the given from the database.
      operationId: findAccount
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
      responses:
        "200":
          description: The account
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AccountDTO'
        "400":
          description: Error with the request
        "404":
          description: Account not found
        "500":
          description: An unexpected event occured
    put:
      tags:
      - account
      summary: Edit an account
      description: This API is updating an existing account based on the provided
        input.
      operationId: editAccount
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AccountDTO'
      responses:
        "200":
          description: The account has been updated
          content:
            application/json: {}
        "400":
          description: Error with the request
        "404":
          description: Account not found
        "500":
          description: An unexpected even occured
    delete:
      tags:
      - account
      summary: Delete an account
      description: "This API is deleting an existing account based on the provided\
        \ id.It will also delete the bans for this account, the link with the realms\
        \ and the warden logs"
      operationId: deleteAccount
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
      responses:
        "204":
          description: The account has been deleted
          content:
            application/json: {}
        "400":
          description: Error with the request
        "404":
          description: Account not found
        "500":
          description: An unexpected even occured
  /v1:
    get:
      tags:
      - account
      summary: Retrieves all accounts
      description: This API is retrieving all accounts from the database.
      operationId: findAllAccounts
      responses:
        "200":
          description: A list of accounts
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                    description: A unique identifier of the account
                  username:
                    type: string
                    description: An username for this account
                  gmLevel:
                    type: string
                    description: The security level of the account
                    enum:
                    - PLAYER
                    - MODERATOR
                    - GAMEMASTER
                    - ADMINISTRATOR
                    - CONSOLE_ONLY
                  sessionKey:
                    type: string
                    description: Session key for this account
                  email:
                    type: string
                    description: An email address for this account. Must be of a valid
                      format
                  joinDate:
                    type: string
                    description: The date at which the user joined
                    format: date-time
                  lastIP:
                    type: string
                    description: The last IP used for this account
                  failedLogins:
                    type: integer
                    description: The amount of failed logins for this account
                  locked:
                    type: boolean
                    description: Indicates whether this account is locked or not
                  lastLogin:
                    type: string
                    description: Last login date for this account
                    format: date-time
                  activeRealmId:
                    type: integer
                    description: An unique identifier on which this account connected
                      the last time
                  expansion:
                    type: string
                    description: An enum value indicating the expansion until which
                      this account has access
                    enum:
                    - VANILLA
                    - BURNING_CRUSADE
                    - WOTLK
                    - CATACLYSM
                    - MOP
                    - WOD
                    - LEGION
                    - BFA
                  mutetime:
                    type: string
                    description: The date at which the account will be unmuted
                    format: date-time
                  locale:
                    type: string
                    description: The locale for this account
                    enum:
                    - ENGLISH
                    - KOREAN
                    - FRENCH
                    - GERMAN
                    - CHINESE
                    - TAIWANESE
                    - SPANISH_SPAIN
                    - SPANISH_LATIN_AMERICA
                    - RUSSIAN
                  os:
                    type: string
                    description: OS used last time for this client
                  playerBot:
                    type: boolean
                    description: Determines whether the account is an user or a playerbot
                description: A list of accounts
        "400":
          description: Error with the request
        "500":
          description: An unexpected even occured
    post:
      tags:
      - account
      summary: Create a new account
      description: This API is creating a new account based on the provided input.
      operationId: addAccount
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AccountDTO'
      responses:
        "201":
          description: The account has been created
          content:
            application/json: {}
        "400":
          description: Error with the request
        "500":
          description: An unexpected even occured
  /v1/bans:
    get:
      tags:
      - account
      summary: Retrieves all bans
      description: This API is retrieving all bans from the database.
      operationId: findAllBans
      responses:
        "200":
          description: A list of bans
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BansDTO'
        "400":
          description: Error with the request
        "500":
          description: An unexpected even occured
    post:
      tags:
      - account
      summary: Create a new ban
      description: This API is creating a new ban based on the provided input.
      operationId: addBan
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/BansDTO'
      responses:
        "201":
          description: The ban has been created
          content:
            application/json: {}
        "400":
          description: Error with the request
        "500":
          description: An unexpected even occured
  /v1/bans/{id}/{bandate}:
    get:
      tags:
      - account
      summary: Retrieves a ban given the id
      description: This API is retrieving the ban with the given id/bandate from the
        database.
      operationId: findBan
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
      - name: bandate
        in: path
        required: true
        schema:
          type: string
          format: date-time
      responses:
        "200":
          description: The ban
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BansDTO'
        "400":
          description: Error with the request
        "404":
          description: Ban not found
        "500":
          description: An unexpected event occured
    put:
      tags:
      - account
      summary: Edit a ban
      description: This API is updating an existing ban based on the provided input.
      operationId: editBan
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
      - name: bandate
        in: path
        required: true
        schema:
          type: string
          format: date-time
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/BansDTO'
      responses:
        "200":
          description: The ban has been updated
          content:
            application/json: {}
        "400":
          description: Error with the request
        "404":
          description: Ban not found
        "500":
          description: An unexpected even occured
    delete:
      tags:
      - account
      summary: Delete a ban
      description: This API is deleting an existing ban based on the provided id.
      operationId: deleteBan
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
      - name: bandate
        in: path
        required: true
        schema:
          type: string
          format: date-time
      responses:
        "204":
          description: The ban has been deleted
          content:
            application/json: {}
        "400":
          description: Error with the request
        "404":
          description: Ban not found
        "500":
          description: An unexpected even occured
  /v1/banip/{ip}/{bandate}:
    get:
      tags:
      - account
      summary: Retrieves a ban given the id
      description: This API is retrieving the ban with the given id/bandate from the
        database.
      operationId: findIpBan
      parameters:
      - name: ip
        in: path
        description: The IP address to search for
        required: true
        schema:
          type: string
        example: 127.0.0.1
      - name: bandate
        in: path
        description: The ban date for this IP
        required: true
        schema:
          type: string
          format: date-time
      responses:
        "200":
          description: The ban
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/IpBannedDTO'
        "400":
          description: Error with the request
        "404":
          description: Ban not found
        "500":
          description: An unexpected event occured
    put:
      tags:
      - account
      summary: Edit a ban
      description: This API is updating an existing ban based on the provided input.
      operationId: editIpBan
      parameters:
      - name: ip
        in: path
        required: true
        schema:
          type: string
      - name: bandate
        in: path
        required: true
        schema:
          type: string
          format: date-time
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/IpBannedDTO'
      responses:
        "200":
          description: The ban has been updated
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/IpBannedDTO'
        "400":
          description: Error with the request
        "404":
          description: Ban not found
        "500":
          description: An unexpected even occured
    delete:
      tags:
      - account
      summary: Delete a ban
      description: This API is deleting an existing ban based on the provided ip.
      operationId: deleteIpBan
      parameters:
      - name: ip
        in: path
        required: true
        schema:
          type: string
      - name: bandate
        in: path
        required: true
        schema:
          type: string
          format: date-time
      responses:
        "204":
          description: The ban has been deleted
          content:
            application/json: {}
        "400":
          description: Error with the request
        "404":
          description: Ban not found
        "500":
          description: An unexpected even occured
  /v1/banip:
    get:
      tags:
      - account
      summary: Retrieves all bans
      description: This API is retrieving all bans from the database.
      operationId: findAllIpBans
      responses:
        "200":
          description: A list of bans
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/IpBannedDTO'
        "400":
          description: Error with the request
        "500":
          description: An unexpected even occured
    post:
      tags:
      - account
      summary: Create a new ban
      description: This API is creating a new ban based on the provided input.
      operationId: addIpBan
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/IpBannedDTO'
      responses:
        "201":
          description: The ban has been created
          content:
            application/json: {}
        "400":
          description: Error with the request
        "500":
          description: An unexpected even occured
components:
  schemas:
    IpBannedDTO:
      type: object
      properties:
        ip:
          type: string
          description: The IP address that is banned
        banDate:
          type: string
          description: The date when the IP was forst banned
          format: date-time
        unbanDate:
          type: string
          description: The date when the IP will be unbanned
          format: date-time
        bannedBy:
          type: string
          description: The name of the character that banned the IP
        banReason:
          type: string
          description: The reason given for the IP ban
    AccountDTO:
      type: object
      properties:
        id:
          type: integer
          description: A unique identifier of the account
        username:
          type: string
          description: An username for this account
        gmLevel:
          type: string
          description: The security level of the account
          enum:
          - PLAYER
          - MODERATOR
          - GAMEMASTER
          - ADMINISTRATOR
          - CONSOLE_ONLY
        sessionKey:
          type: string
          description: Session key for this account
        email:
          type: string
          description: An email address for this account. Must be of a valid format
        joinDate:
          type: string
          description: The date at which the user joined
          format: date-time
        lastIP:
          type: string
          description: The last IP used for this account
        failedLogins:
          type: integer
          description: The amount of failed logins for this account
        locked:
          type: boolean
          description: Indicates whether this account is locked or not
        lastLogin:
          type: string
          description: Last login date for this account
          format: date-time
        activeRealmId:
          type: integer
          description: An unique identifier on which this account connected the last
            time
        expansion:
          type: string
          description: An enum value indicating the expansion until which this account
            has access
          enum:
          - VANILLA
          - BURNING_CRUSADE
          - WOTLK
          - CATACLYSM
          - MOP
          - WOD
          - LEGION
          - BFA
        mutetime:
          type: string
          description: The date at which the account will be unmuted
          format: date-time
        locale:
          type: string
          description: The locale for this account
          enum:
          - ENGLISH
          - KOREAN
          - FRENCH
          - GERMAN
          - CHINESE
          - TAIWANESE
          - SPANISH_SPAIN
          - SPANISH_LATIN_AMERICA
          - RUSSIAN
        os:
          type: string
          description: OS used last time for this client
        playerBot:
          type: boolean
          description: Determines whether the account is an user or a playerbot
    BansDTO:
      type: object
      properties:
        id:
          type: integer
          description: An unique identifier for this ban
        date:
          type: string
          description: Date at which this ban has been issued
          format: date-time
        unbanDate:
          type: string
          description: The date when this account will be automatically unbanned
          format: date-time
        bannedBy:
          type: string
          description: The character that banned this account
        banReason:
          type: string
          description: The reason for the ban
        active:
          type: boolean
          description: Indicates whether the ban is currently active or not